version: '3.9'

services:
  api:
    build: node
    image: node-express-dev:1.0
    tty: true
    volumes:
      - ./node/api:/app
    ports:
      - "5000:5000"
  
  vue:
    build: vue
    container_name: vue
    ports:
      - '8080:8080'
    volumes:
      - ./vue:/app
    stdin_open: true
    tty: true
  
  db:
    platform: linux/x86_64 
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user01
      MYSQL_PASSWORD: password

volumes:
  db_data: